import type { GetServerSideProps, NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { Button } from "../components";
import { getServerAuthSession } from "../server/common/get-server-auth-session";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next Task</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-slate-500 ">
        <Button
          onClick={() => signIn("github")}
          className="absolute right-0 m-3 bg-emerald-600 hover:bg-emerald-700"
        >
          Login With Github
        </Button>

        <div className="h-full flex flex-col items-center justify-center space-y-10">
          <div className="text-center">
            <h1 className="text-5xl font-bold text-slate-50">Next Task</h1>
            <p className="text-xl text-slate-100">
              Keep track of the daily tasks in your life.
            </p>
          </div>
          <div className="relative h-[50%] w-[50%]">
            <Image
              src="/next_task.svg"
              alt="next_task"
              layout="fill"
              className="absolute"
            />
          </div>
        </div>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await getServerAuthSession(ctx);
  if (session) {
    return {
      redirect: {
        destination: "/app",
        permanent: false,
      },
    };
  }
  return {
    props: {
      session,
    },
  };
};

export default Home;
